server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://database-1.ciky67sqvyri.us-east-1.rds.amazonaws.com/project2
    username: javafs
    password: 09oXbzXRCQsLFhd9KcYH
    driver-class-name: org.postgresql.Driver
